/**
 * @file above_and_below.ts — Above and Below engine wrapper (family: numeric_math).
 * @description Configures GenericTableauEngine for Above and Below.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Above and Below',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [4,4,4,4,4,4,4,4],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic variable-step foundation config (used by MathScreen + _genericMath engine) ───
import type { MathConfig } from './_genericMath';

export const MATH_CONFIG: MathConfig = {
  name: "Above and Below",
  decks: 1,
  numFoundations: 8,
  foundationBaseRanks: [1,1,1,1,13,13,13,13],
  foundationSteps: [1,1,1,1,1,1,1,1],
  foundationsModular: false,
  foundationDirections: ["asc","asc","asc","asc","desc","desc","desc","desc"],
  foundationSuitRule: "same-suit",
  numWastePiles: 4,
  wasteToWasteAllowed: false,
  dealAllOnDraw: false,
  mustDistributeStockFirst: false,
  stockRecycle: "none",
  winCondition: 'all-on-foundations',
};
