/**
 * @file aces_and_kings.ts — Aces and Kings engine wrapper (family: pairs).
 * @description Configures GenericTableauEngine for Aces and Kings.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Aces and Kings',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [4,4,4,4,4,4,4,4],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic pair-removal config (used by PairsScreen + _genericPairs engine) ───
import type { PairsConfig } from './_genericPairs';

export const PAIRS_CONFIG: PairsConfig = {
  name: "Aces and Kings",
  decks: 1,
  layoutKind: "columns",
  columns: [4,4,4,4,4,4,4,4],
  pairRule: "rank-match",
  stockEnabled: true,
  stockRecycle: "none",
  stockDrawCount: 1,
  winCondition: "layout-cleared",
};
