/**
 * @file auld_lang_syne.ts — Auld Lang Syne engine wrapper (family: numeric_math).
 * @description Configures GenericTableauEngine for Auld Lang Syne.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Auld Lang Syne',
  decks: 1,
  tableauColumns: 4,
  tableauDealPattern: [1,1,1,1],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 4,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic variable-step foundation config (used by MathScreen + _genericMath engine) ───
import type { MathConfig } from './_genericMath';

export const MATH_CONFIG: MathConfig = {
  name: "Auld Lang Syne",
  decks: 1,
  numFoundations: 4,
  foundationBaseRanks: [1,1,1,1],
  foundationSteps: [1,1,1,1],
  foundationsModular: false,
  foundationSuitRule: "any",
  numWastePiles: 4,
  wasteToWasteAllowed: false,
  dealAllOnDraw: true,
  mustDistributeStockFirst: false,
  stockRecycle: "none",
  winCondition: 'all-on-foundations',
};
