/**
 * @file bakers_dozen.ts — Baker's Dozen engine wrapper.
 * @description Configures GenericTableauEngine for Baker's Dozen. Family: modern_hybrid.
 * Generated by tmp/generate-25-more-engines.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Baker\'s Dozen',
  decks: 1,
  tableauColumns: 13,
  tableauDealPattern: [4,4,4,4,4,4,4,4,4,4,4,4,4],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'forbidden',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
