/**
 * @file beetle.ts — Beetle engine wrapper.
 * @description Configures GenericTableauEngine for Beetle. Family: spider.
 * Generated by tmp/generate-batch5.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Beetle',
  decks: 2,
  tableauColumns: 10,
  tableauDealPattern: [6,6,6,6,5,5,5,5,5,5],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 8,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'same-suit',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 10,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic Spider config (used by SpiderV2Screen + _genericSpider engine) ───
import type { SpiderConfig } from './_genericSpider';

export const SPIDER_CONFIG: SpiderConfig = {
  name: "Beetle",
  decks: 2,
  tableauColumns: 10,
  tableauDealPattern: [6,6,6,6,6,5,5,5,5,5],
  tableauFaceUpFromBottom: 1,
  suitMode: 4,
  stackingRule: "alternating-colors",
  emptyColumnRule: "any",
  stockEnabled: true,
  stockDealCount: 5,
  allowDrawWithEmptyColumn: false,
  allowAnyBlockMove: false,
};
