/**
 * @file belle_lucie_fr.ts — La Belle Lucie (FR) engine wrapper.
 * @description Configures GenericTableauEngine for La Belle Lucie (FR). Family: french_traditional.
 * Generated by tmp/generate-batch5.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'La Belle Lucie (FR)',
  decks: 1,
  tableauColumns: 18,
  tableauDealPattern: [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'same-suit',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 2,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
