/**
 * @file betsy_ross.ts — Betsy Ross engine wrapper (family: numeric_math).
 * @description Configures GenericTableauEngine for Betsy Ross.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Betsy Ross',
  decks: 1,
  tableauColumns: 4,
  tableauDealPattern: [1,1,1,1],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 4,
  reservePileSize: 1,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic variable-step foundation config (used by MathScreen + _genericMath engine) ───
import type { MathConfig } from './_genericMath';

export const MATH_CONFIG: MathConfig = {
  name: "Betsy Ross",
  decks: 1,
  numFoundations: 4,
  foundationBaseRanks: [1,2,3,4],
  foundationSteps: [1,2,3,4],
  foundationsModular: true,
  foundationSuitRule: "any",
  numWastePiles: 4,
  wasteToWasteAllowed: true,
  dealAllOnDraw: false,
  mustDistributeStockFirst: false,
  stockRecycle: "unlimited",
  winCondition: 'all-on-foundations',
};
