/**
 * @file big_ben.ts — Big Ben engine wrapper.
 * @description Configures the shared GenericDistributionEngine
 * (./_genericDistribution.ts) for Big Ben.
 *
 * Generated by tmp/generate-30-engines.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, defaultPileForRank, type DistributionConfig, type DistributionGameState, type DistributionAction } from './_genericDistribution';

export const CONFIG: DistributionConfig = {
  name: 'Big Ben',
  decks: 2,
  clockPiles: 12,
  cardsPerPile: 5,
  hasCenterPile: true,
  centerPileSize: 4,
  pileForRank: defaultPileForRank,
};

export function createInitialState(): DistributionGameState {
  return createInitialStateFor(CONFIG);
}

export const gameReducer = genericReducer;
export type { DistributionGameState as GameState, DistributionAction as Action };
