/**
 * @file brigade.ts — Brigade engine wrapper.
 * @description Configures GenericTableauEngine for Brigade. Family: royal_coronation.
 * Generated by tmp/generate-25-more-engines.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Brigade',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [4,4,4,4,4,4,4,4],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 5,
  reservePileSize: 1,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
