/**
 * @file canfield_classic.ts — Canfield (classique) engine wrapper.
 * @description Configures the shared GenericTableauEngine (./_genericTableau.ts)
 * with the rules specific to Canfield (classique). Family: Canfield.
 *
 * Generated by tmp/generate-30-engines.js — do not edit by hand; edit the
 * generator instead and re-run it.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Canfield (classique)',
  decks: 1,
  tableauColumns: 4,
  tableauDealPattern: [1,1,1,1],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 1,
  reservePileSize: 13,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 'variable' as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 3,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
