/**
 * @file cheops.ts — Cheops engine wrapper (family: pyramid).
 * @description Configures GenericTableauEngine for Cheops.
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Cheops',
  decks: 1,
  tableauColumns: 7,
  tableauDealPattern: [1,2,3,4,5,6,7],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic pair-removal config (used by PairsScreen + _genericPairs engine) ───
import type { PairsConfig } from './_genericPairs';

export const PAIRS_CONFIG: PairsConfig = {
  name: "Cheops",
  decks: 1,
  layoutKind: "pyramid",
  rows: [1,2,3,4,5,6,7],
  pairRule: "sequence-1",
  stockEnabled: true,
  stockRecycle: "unlimited",
  stockDrawCount: 1,
  winCondition: "layout-cleared",
};
