/**
 * @file chessboard.ts — Chessboard engine wrapper.
 * @description Configures the shared GenericTableauEngine (./_genericTableau.ts)
 * with the rules specific to Chessboard. Family: Castle.
 *
 * Generated by tmp/generate-30-engines.js — do not edit by hand; edit the
 * generator instead and re-run it.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Chessboard',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [6,6,6,6,6,6,6,6],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 'variable' as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
