/**
 * @file clock_solitaire.ts — Clock Solitaire engine wrapper.
 * @description Configures the shared GenericDistributionEngine
 * (./_genericDistribution.ts) for Clock Solitaire.
 *
 * Generated by tmp/generate-30-engines.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, defaultPileForRank, type DistributionConfig, type DistributionGameState, type DistributionAction } from './_genericDistribution';

export const CONFIG: DistributionConfig = {
  name: 'Clock Solitaire',
  decks: 1,
  clockPiles: 12,
  cardsPerPile: 4,
  hasCenterPile: true,
  centerPileSize: 4,
  pileForRank: defaultPileForRank,
};

export function createInitialState(): DistributionGameState {
  return createInitialStateFor(CONFIG);
}

export const gameReducer = genericReducer;
export type { DistributionGameState as GameState, DistributionAction as Action };
