/**
 * @file crapette.ts — Crapette engine wrapper.
 * @description Configures GenericTableauEngine for Crapette. Family: russian_bezique.
 * Generated by tmp/generate-25-more-engines.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Crapette',
  decks: 2,
  tableauColumns: 8,
  tableauDealPattern: [4,4,4,4,4,4,4,4],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 1,
  reservePileSize: 13,
  reserveFaceUp: false,
  foundations: 8,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
