/**
 * @file crystal_cluster.ts — Crystal Cluster engine wrapper (family: mahjong_cards).
 * @description Configures GenericTableauEngine for Crystal Cluster.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Crystal Cluster',
  decks: 2,
  tableauColumns: 7,
  tableauDealPattern: [6,6,6,6,6,6,6],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 8,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic pair-removal config (used by PairsScreen + _genericPairs engine) ───
import type { PairsConfig } from './_genericPairs';

export const PAIRS_CONFIG: PairsConfig = {
  name: "Crystal Cluster",
  decks: 2,
  layoutKind: "columns",
  columns: [12,12,12,12,12,12,12,12,12],
  pairRule: "rank-match",
  stockEnabled: false,
  stockRecycle: "none",
  stockDrawCount: 0,
  winCondition: "layout-cleared",
};
