/**
 * @file display.ts — Display engine wrapper (family: modern_hybrid).
 * @description Configures GenericTableauEngine for Display.
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Display',
  decks: 2,
  tableauColumns: 10,
  tableauDealPattern: [5,5,5,5,5,5,5,5,5,5],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 8,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
