/**
 * @file drapeaux.ts — La Réussite des Drapeaux engine wrapper.
 * @description Configures GenericTableauEngine for La Réussite des Drapeaux. Family: french_traditional.
 * Generated by tmp/generate-batch5.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'La Réussite des Drapeaux',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [4,4,4,4,4,4,4,4],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
