/**
 * @file grandfathers_clock.ts — Grandfather's Clock engine wrapper.
 * @description Configures the shared GenericDistributionEngine
 * (./_genericDistribution.ts) for Grandfather's Clock.
 *
 * Generated by tmp/generate-30-engines.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, defaultPileForRank, type DistributionConfig, type DistributionGameState, type DistributionAction } from './_genericDistribution';

export const CONFIG: DistributionConfig = {
  name: 'Grandfather\'s Clock',
  decks: 1,
  clockPiles: 12,
  cardsPerPile: 4,
  hasCenterPile: false,
  centerPileSize: 0,
  pileForRank: defaultPileForRank,
};

export function createInitialState(): DistributionGameState {
  return createInitialStateFor(CONFIG);
}

export const gameReducer = genericReducer;
export type { DistributionGameState as GameState, DistributionAction as Action };
