/**
 * @file hickory_dickory_dock.ts — Hickory Dickory Dock engine wrapper (family: clock).
 * @description Configures GenericDistributionEngine for Hickory Dickory Dock.
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, defaultPileForRank, type DistributionConfig, type DistributionGameState, type DistributionAction } from './_genericDistribution';

export const CONFIG: DistributionConfig = {
  name: 'Hickory Dickory Dock',
  decks: 1,
  clockPiles: 12,
  cardsPerPile: 4,
  hasCenterPile: true,
  centerPileSize: 4,
  pileForRank: defaultPileForRank,
};

export function createInitialState(): DistributionGameState {
  return createInitialStateFor(CONFIG);
}

export const gameReducer = genericReducer;
export type { DistributionGameState as GameState, DistributionAction as Action };
