/**
 * @file la_cigale.ts — La Cigale engine wrapper.
 * @description Configures GenericTableauEngine for La Cigale. Family: modern_hybrid.
 * Generated by tmp/generate-batch5.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'La Cigale',
  decks: 1,
  tableauColumns: 7,
  tableauDealPattern: [1,2,3,4,5,6,7],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'same-suit',
  stackingDirection: 'descending',
  emptyColumnRule: 'king-only',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
