/**
 * @file la_fourmi.ts — La Fourmi engine wrapper.
 * @description Configures GenericTableauEngine for La Fourmi. Family: modern_hybrid.
 * Generated by tmp/generate-batch5.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'La Fourmi',
  decks: 1,
  tableauColumns: 7,
  tableauDealPattern: [1,2,3,4,5,6,7],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any-different-color',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 3,
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
