/**
 * @file mrs_mop.ts — Mrs. Mop engine wrapper (family: spider).
 * @description Configures GenericTableauEngine for Mrs. Mop.
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Mrs. Mop',
  decks: 2,
  tableauColumns: 13,
  tableauDealPattern: [8,8,8,8,8,8,8,8,8,8,8,8,8],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 8,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'same-suit',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic Spider config (used by SpiderV2Screen + _genericSpider engine) ───
import type { SpiderConfig } from './_genericSpider';

export const SPIDER_CONFIG: SpiderConfig = {
  name: "Mrs. Mop",
  decks: 2,
  tableauColumns: 13,
  tableauDealPattern: [8,8,8,8,8,8,8,8,8,8,8,8,8],
  tableauFaceUpFromBottom: 'all',
  suitMode: 4,
  stackingRule: "same-suit",
  emptyColumnRule: "any",
  stockEnabled: false,
  stockDealCount: 0,
  allowDrawWithEmptyColumn: false,
  allowAnyBlockMove: false,
};
