/**
 * @file nestor.ts — Nestor engine wrapper (family: pairs).
 * @description Configures GenericTableauEngine for Nestor.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Nestor',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [6,6,6,6,6,6,6,6],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'forbidden',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic pair-removal config (used by PairsScreen + _genericPairs engine) ───
import type { PairsConfig } from './_genericPairs';

export const PAIRS_CONFIG: PairsConfig = {
  name: "Nestor",
  decks: 1,
  layoutKind: "columns",
  columns: [6,6,6,6,6,6,6,6],
  pairRule: "rank-match",
  stockEnabled: false,
  stockRecycle: "none",
  stockDrawCount: 0,
  winCondition: "layout-cleared",
};
