/**
 * @file pumpkin.ts — Pumpkin engine wrapper (family: tripeaks_golf).
 * @description Configures GenericTableauEngine for Pumpkin.
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Pumpkin',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [4,4,4,4,4,4,4,4],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic ±1 chain config (used by GolfScreen + _genericGolf engine) ───
import type { GolfConfig } from './_genericGolf';

export const GOLF_CONFIG: GolfConfig = {
  name: "Pumpkin",
  decks: 1,
  layoutKind: "columns",
  shape: [4,4,4,4,4,4,4,4],
  circular: false,
  stockEnabled: true,
  stockRecycle: "none",
  stockDrawCount: 1,
  comboEnabled: false,
  pointsPerCard: 1,
  seedWasteFromStock: true,
  winCondition: 'layout-cleared',
};
