/**
 * @file quatre_coins.ts — Patience des Quatre Coins engine wrapper.
 * @description Configures GenericTableauEngine for Patience des Quatre Coins. Family: french_traditional.
 * Generated by tmp/generate-25-more-engines.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Patience des Quatre Coins',
  decks: 2,
  tableauColumns: 4,
  tableauDealPattern: [1,1,1,1],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 4,
  reservePileSize: 1,
  reserveFaceUp: true,
  foundations: 8,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'same-suit',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
