/**
 * @file racing_demon.ts — Racing Demon engine wrapper (family: multiplayer).
 * @description Configures GenericTableauEngine for Racing Demon.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Racing Demon',
  decks: 1,
  tableauColumns: 4,
  tableauDealPattern: [1,1,1,1],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 1,
  reservePileSize: 13,
  reserveFaceUp: false,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 3,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
