/**
 * @file scuffle.ts — Scuffle engine wrapper.
 * @description Configures GenericTableauEngine for Scuffle. Family: modern_hybrid.
 * Generated by tmp/generate-batch5.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Scuffle',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [2,2,2,2,2,2,2,2],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 4,
  reservePileSize: 1,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
