/**
 * @file spite_and_malice.ts — Spite and Malice engine wrapper (family: multiplayer).
 * @description Configures GenericTableauEngine for Spite and Malice.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Spite and Malice',
  decks: 2,
  tableauColumns: 4,
  tableauDealPattern: [1,1,1,1],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 1,
  reservePileSize: 26,
  reserveFaceUp: false,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
