/**
 * @file stalactites.ts — Stalactites engine wrapper (family: freecell).
 * @description Configures GenericTableauEngine for Stalactites.
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Stalactites',
  decks: 1,
  tableauColumns: 8,
  tableauDealPattern: [6,6,6,6,6,6,6,6],
  tableauFaceUpFromBottom: 'all',
  freeCells: 0,
  reservePiles: 2,
  reservePileSize: 1,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'forbidden',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
