/**
 * @file travellers.ts — Travellers (Voyageurs) engine wrapper (family: clock).
 * @description Configures GenericDistributionEngine for Travellers (Voyageurs).
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, defaultPileForRank, type DistributionConfig, type DistributionGameState, type DistributionAction } from './_genericDistribution';

export const CONFIG: DistributionConfig = {
  name: 'Travellers (Voyageurs)',
  decks: 1,
  clockPiles: 12,
  cardsPerPile: 4,
  hasCenterPile: false,
  centerPileSize: 0,
  pileForRank: defaultPileForRank,
};

export function createInitialState(): DistributionGameState {
  return createInitialStateFor(CONFIG);
}

export const gameReducer = genericReducer;
export type { DistributionGameState as GameState, DistributionAction as Action };
