/**
 * @file triple_peaks.ts — Triple Peaks engine wrapper (family: tripeaks_golf).
 * @description Configures GenericTableauEngine for Triple Peaks.
 * Generated by tmp/generate-batch6.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Triple Peaks',
  decks: 1,
  tableauColumns: 10,
  tableauDealPattern: [1,2,3,4,3,2,1,3,4,3],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'any',
  stackingDirection: 'descending',
  emptyColumnRule: 'any',
  stockEnabled: true,
  stockDrawCount: 1,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: false,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic ±1 chain config (used by GolfScreen + _genericGolf engine) ───
import type { GolfConfig } from './_genericGolf';

export const GOLF_CONFIG: GolfConfig = {
  name: "Triple Peaks",
  decks: 1,
  layoutKind: "peaks",
  shape: [3,6,9,10],
  hideUpperRows: 3,
  circular: true,
  stockEnabled: true,
  stockRecycle: "none",
  stockDrawCount: 1,
  comboEnabled: true,
  pointsPerCard: 1,
  seedWasteFromStock: true,
  winCondition: 'layout-cleared',
};
