/**
 * @file will_o_wisp.ts — Will o' the Wisp engine wrapper.
 * @description Configures GenericTableauEngine for Will o' the Wisp. Family: spider.
 * Generated by tmp/generate-batch5.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Will o\' the Wisp',
  decks: 1,
  tableauColumns: 7,
  tableauDealPattern: [3,3,3,3,3,3,3],
  tableauFaceUpFromBottom: 1,
  freeCells: 0,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'same-suit',
  stackingDirection: 'descending',
  emptyColumnRule: 'king-only',
  stockEnabled: true,
  stockDrawCount: 7,
  stockRecycle: 'none',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };

// ─── Authentic Spider config (used by SpiderV2Screen + _genericSpider engine) ───
import type { SpiderConfig } from './_genericSpider';

export const SPIDER_CONFIG: SpiderConfig = {
  name: "Will o' the Wisp",
  decks: 1,
  tableauColumns: 7,
  tableauDealPattern: [3,3,3,3,3,3,3],
  tableauFaceUpFromBottom: 1,
  suitMode: 4,
  stackingRule: "same-suit",
  emptyColumnRule: "king-only",
  stockEnabled: true,
  stockDealCount: 5,
  allowDrawWithEmptyColumn: false,
  allowAnyBlockMove: false,
};
