/**
 * @file yukon_cells.ts — Yukon Cells engine wrapper (family: yukon).
 * @description Configures GenericTableauEngine for Yukon Cells.
 * Generated by tmp/generate-batch-final.js — do not edit by hand.
 */
import { createInitialStateFor, gameReducer as genericReducer, type TableauConfig, type GameState, type Action } from './_genericTableau';

export const CONFIG: TableauConfig = {
  name: 'Yukon Cells',
  decks: 1,
  tableauColumns: 7,
  tableauDealPattern: [1,6,7,8,9,10,11],
  tableauFaceUpFromBottom: 1,
  freeCells: 4,
  reservePiles: 0,
  reservePileSize: 0,
  reserveFaceUp: true,
  foundations: 4,
  foundationBaseRank: 1 as any,
  foundationDirection: 'ascending',
  stackingRule: 'alternating-colors',
  stackingDirection: 'descending',
  emptyColumnRule: 'king-only',
  stockEnabled: false,
  stockDrawCount: 1,
  stockRecycle: 'unlimited',
  tableauRedeals: 0,
  multiCardMove: true,
};

export function createInitialState(seed?: number): GameState {
  return createInitialStateFor(CONFIG, seed);
}

export const gameReducer = genericReducer;
export type { GameState, Action };
